### ISSUE TITLE
No info about travis addon

### ISSUE THREAD

**Issue by antonmarin** [codeclimate/php-test-reporter#53]
No info about how to configure travis addon to use custom coverage-report file 
(test-reporter [--coverage-report COVERAGE-REPORT])

For example:

```
addons:
    code_climate:
        repo_token: ****
        coverage_report: tests/logs/clover.xml
```
